### ISSUE TITLE
Feedback (Fabio & Nils)

### ISSUE THREAD

**Issue by NLaudenbach** [nel-nuss/FOSSGIS-Project#1]
Hi, here is our feedback for your work so far.
Since we couldn't download the files and you only uploaded batchfiles, there wasn't much we could test. However, the downloading of the various files was very neat and clearly documented

**Comment by nel-nuss** [comment]
Could you please describe the issues you had with downloading? Were you not able to execute the batch files? I can provide the layers for you so you can test the intermediate stage of the QGIS model as well.
