### ISSUE TITLE
Files displayed as invalid data source 

### ISSUE THREAD

**Issue by NLaudenbach** [nel-nuss/FOSSGIS-Project#2]
Hi, I followed the instructions in your readme file until I got the geojason files as an output.  Now I have the problem that I can't open them in QGIS, because they are displayed as invalid files. Do you know what I could do about that problem?

**Comment by nel-nuss** [comment]
Hi, 
sometimes there is a problem with the ohsome API or the user inputs. Could you please open one of the downloaded .geojson layers in the editor and tell me what the content of the file is? 
Also make sure that you put the date in in the correct format, from experience that is the number one reason for download failure.

**Comment by NLaudenbach** [comment]
Thanks for the help. I had entered the date incorrectly. Now everything works very well.
